In [1]:
import numpy as np

In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [4]:
arr = np.array([1,2,3])

In [5]:
arr

array([1, 2, 3])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((3,2),8)

array([[8, 8],
       [8, 8],
       [8, 8]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [16]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [20]:
myarr = np.array([[1,2,3],[4,5,6],[6,7,8],[11,12,13]])

In [21]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [11, 12, 13]])

In [22]:
myarr.shape

(4, 3)

In [23]:
myarr.size

12

In [24]:
myarr.ndim #dimention 2D

2

In [28]:
myarr.dtype

dtype('int32')

In [30]:
myarr = np.array([[1,2,3],[4,5,6],[6,7,8],[11,12,13]],dtype='float32')

In [31]:
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 6.,  7.,  8.],
       [11., 12., 13.]], dtype=float32)

In [34]:
n = myarr.astype('float64')

In [36]:
n.dtype

dtype('float64')

In [37]:
myarr = np.array([[1,2,3],[4,5,6],[6,7,8],[11,12,13]])

In [38]:
myarr.shape

(4, 3)

In [46]:
reshaped = myarr.reshape((2,6))

In [44]:
reshaped

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8, 11, 12, 13]])

In [41]:
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [11, 12, 13]])

In [48]:
myarr.flatten()

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8, 11, 12, 13])