In [1]:
import numpy as np

In [2]:
arr = np.array([24,4,3,23])

In [3]:

arr.dtype

dtype('int32')

In [4]:
arr.astype("float64")

array([24.,  4.,  3., 23.])

In [6]:
arr2 = np.array([23,4,3,23],dtype="float32")

In [7]:
arr2

array([23.,  4.,  3., 23.], dtype=float32)

In [8]:
arr2.nbytes

16

In [9]:
arr.nbytes

16

In [10]:
arr = np.array([1+2j,3+4j,5+6j],dtype='complex128')  #complex no

In [11]:
arr

array([1.+2.j, 3.+4.j, 5.+6.j])