In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[6,7,8],[11,12,13]])

In [5]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [11, 12, 13]])

In [6]:
flat=arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8, 11, 12, 13])

In [8]:
flat[0]

1

In [9]:
flat[3]

4

In [11]:
flat[3:5]

array([4, 5])

In [12]:
flat[:5] #same as flat[0:5]

array([1, 2, 3, 4, 5])

In [13]:
flat[3:] #same as flat[3:length(arr)]

array([ 4,  5,  6,  6,  7,  8, 11, 12, 13])

In [14]:
flat[::2]

array([ 1,  3,  5,  6,  8, 12])

In [15]:
flat

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8, 11, 12, 13])

In [16]:
b = flat[3:7]

In [17]:
b

array([4, 5, 6, 6])

In [18]:
b[0] = 4444

In [19]:
b

array([4444,    5,    6,    6])

In [20]:
flat

array([   1,    2,    3, 4444,    5,    6,    6,    7,    8,   11,   12,
         13])

In [21]:
arr = np.array([1,23,43,34,5,56,234,43])

In [23]:
arr[[1,4,6]] # new array of mentioned indices

array([ 23,   5, 234])

In [25]:
arr[arr>23] #boolean masking

array([ 43,  34,  56, 234,  43])

In [27]:
arr=np.array([[2,3,4],[4,5,6],[7,8,9]])

In [28]:
arr

array([[2, 3, 4],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.shape

(3, 3)

In [30]:
deci=np.array([1.1,2.2,3.3])

In [31]:
deci.astype('int32')

array([1, 2, 3])

In [37]:
arr=np.array([1,2,3,4,5,6])

In [43]:
inx=[1,3,5]

In [44]:
print(arr[inx])

[2 4 6]


In [45]:
arr1=np.array([2,3,45,6,32,23,45,532,12])

In [ ]:
arr1.