In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
  np.sum(arr, axis=0) #column

array([12, 15, 18])

In [10]:
 np.sum(arr, axis=1) #row

array([ 6, 15, 24])

In [12]:
arr[0][1]

2

In [13]:
arr[0,1]

2

In [14]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [15]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [16]:
print(arr3D[:, 0, :])


[[1 2 3]
 [7 8 9]]


In [17]:
print(arr3D[0, 0, :])

[1 2 3]


In [19]:
print(arr3D[0, :, 0])

[1 4]


In [21]:
print(arr3D[:, 0, 0])

[1 7]


In [22]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])